using AutoFixture;
using AutoFixture.AutoMoq;
using AutoFixture.Xunit3;

namespace LoggerConsoleApplication.Tests.Attributes;

/// <summary>
/// Provides auto-generated data specimens generated by AutoFixture as an extension to xUnit.net's Theory attribute,
/// and uses Moq to create those auto-generated data specimens.
/// </summary>
public class AutoMoqDataAttribute : AutoDataAttribute
{
    /// <summary>
    /// Creates and configures the shared AutoFixture fixture with Moq support.
    /// </summary>
    internal static IFixture CreateFixture()
    {
        var fixture = new Fixture()
            .Customize(new AutoMoqCustomization { ConfigureMembers = true });

        fixture.Behaviors.OfType<ThrowingRecursionBehavior>().ToList().ForEach(b => fixture.Behaviors.Remove(b));
        fixture.Behaviors.Add(new OmitOnRecursionBehavior());
        return fixture;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="AutoMoqDataAttribute"/> class.
    /// </summary>
    public AutoMoqDataAttribute()
        : base(CreateFixture)
    {
    }
}
